### ISSUE TITLE
[CN] Crash on mismatch function and `spec` declarations

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#607] opened 2024-10-02 22:44 UTC
The following crashes CN: 
```
void crash_spec();
/*@
spec crash_spec(i32 foo);
requires true;
ensures true; 
@*/
```

Current behavior: 
```
cn verify src/example-archive/simple-examples/inprogress/crash_spec.c
cn: internal error, uncaught exception:
    Invalid_argument("List.combine")
    Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
    Called from Cn__Core_to_mucore.normalise_fun_map_decl in file "backend/cn/lib/core_to_mucore.ml", line 1358, characters 14-69
    Called from Cn__Core_to_mucore.normalise_fun_map.(fun) in file "backend/cn/lib/core_to_mucore.ml", line 1384, characters 12-282
    Called from Pmap.fold in file "pmap.ml", line 156, characters 15-38
    Called from Cn__Core_to_mucore.normalise_fun_map in file "backend/cn/lib/core_to_mucore.ml", line 1380, characters 4-922
    Called from Cn__Core_to_mucore.normalise_file in file "backend/cn/lib/core_to_mucore.ml", line 1547, characters 4-221
    Called from Dune__exe__Main.with_well_formedness_check in file "backend/cn/bin/main.ml", line 172, characters 8-135
    Re-raised at Dune__exe__Main.with_well_formedness_check in file "backend/cn/bin/main.ml", line 190, characters 4-69
    Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
    Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
```

Desired behavior: CN reports an error saying the arguments are mismatched. 

Related: #248 (probably the same issue), #362 

CN version: `git-9dc7bc505 [2024-10-01 13:28:14 -0400]`

cc: @lwli11

**Comment by dc-mak** [comment] 2024-10-30 12:59
Duplicate of #248

**Closed as completed by dc-mak** 2024-10-30 12:59 UTC
Labels: ui/ux, cn
