### ISSUE TITLE
[CN] Crash on array resource with condition

### ISSUE THREAD

**Issue by mu-mu-mu** [rems-project/cerberus#392] opened 2024-07-16 21:24 UTC
Hello,

I encountered an error when applying CN to a program using an array resource with its condition.

$cn --version
CN version: git-ca7bc60f3
$ocaml --version
The OCaml toplevel, version 4.14.1

```
cn: internal error, uncaught exception:
    Invalid_argument("List.combine")
    Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
    Called from Stdlib__List.combine in file "list.ml", line 305, characters 36-49
    Called from Stdlib__List.combine in file "list.ml", line 305, characters 36-49
    Called from Dune__exe__Core_to_mucore.normalise_fun_map_decl in file "backend/cn/core_to_mucore.ml", line 1328, characters 19-74
    Called from Dune__exe__Core_to_mucore.normalise_fun_map.(fun) in file "backend/cn/core_to_mucore.ml", line 1351, characters 15-193
    Called from Pmap.fold in file "pmap.ml", line 156, characters 15-38
    Called from Dune__exe__Core_to_mucore.normalise_fun_map in file "backend/cn/core_to_mucore.ml", line 1349, characters 2-759
    Called from Dune__exe__Core_to_mucore.normalise_file in file "backend/cn/core_to_mucore.ml", line 1511, characters 4-185
    Called from Dune__exe__Main.main in file "backend/cn/main.ml", line 227, characters 19-117
    Re-raised at Dune__exe__Main.main in file "backend/cn/main.ml", line 247, characters 6-71
    Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
    Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44

```

Code
```
#define N 3

extern void make_bool(char *p,  unsigned int n);
/*@spec make_bool(pointer p, pointer q, u32 n);
  requires take a1 = each(u32 i; i < n) { Owned<char>( array_shift<char>(p, i)) };
  ensures
    take b1 = each(u32 i; i < n) { Owned<char>( array_shift<char>(p, i)) };
    each(u32 i; i < n) { b1[i] == (a1[i] ? 1u8 : 0u8 ) };
@*/

void test(char *p)
/*@
  requires take a1 = each(u32 i; i < 3u32) { Owned<char>( array_shift<char>(p, i)) };
  ensures  take b1 = each(u32 i; i < 3u32) { Owned<char>( array_shift<char>(p, i)) };
@*/
{
	make_bool(p, N);
}
```

To my understanding, this code is valid. I referred to:
 https://github.com/rems-project/cerberus/blob/master/tests/cn/memcpy.c 

Thank you.

**Comment by dc-mak** [comment] 2024-07-17 09:23
The spec doesn't match the function type (extra `pointer q`).

Closing as duplicate of https://github.com/rems-project/cerberus/issues/248

**Closed as completed by dc-mak** 2024-07-17 09:23 UTC
Labels: cn
