### ISSUE TITLE
[CN] Implement `foo->bar` member syntax for pointers in spec language

### ISSUE THREAD

**Issue by dc-mak** [rems-project/cerberus#328] opened 2024-06-16 21:04 UTC

**Comment by dc-mak** [comment] 2024-06-24 10:53
Duplicate of https://github.com/rems-project/cerberus/issues/329

**Comment by ZippeyKeys12** [comment] 2024-06-25 00:47
There isn't a description, but wasn't this issue meant to be about `x->y` being sugar for `(*x).y`?

So not a duplicate of #329?

**Comment by cp526** [comment] 2024-06-25 07:05
Indeed

**Comment by dc-mak** [comment] 2024-06-25 08:44
Oops yes thanks

**Comment by septract** [comment] 2024-07-22 14:33
@dc-mak this issue can be closed

**Closed as completed** 2024-07-22 14:56 UTC
Labels: cn
