### ISSUE TITLE
[CN] Better error message for mismatched index types for `each (..) { ..  }`

### ISSUE THREAD

**Issue by lwli11** [rems-project/cerberus#533] opened 2024-08-25 19:25 UTC
For the code: 
```c
void readex(char* tmp)
/*@
        requires take a1 = each(i32 j; 0i32 <= j && j < 1i32) { Owned<char>(array_shift<char>(tmp,j)) };
@*/
{
        return;
}
int tmp()
{
        char tmp[2]={'H', 'i'};
        readex(tmp);
        return 1;
}
````

I get: 
```sh
cn verify read_example.c
[1/2]: tmp
read_example.c:14:2: error: Missing resource for calling function readex
        readex(tmp);
        ^~~~~~~~~~~
Resource needed: each(i32 j; (0i32 <= j) && (j < 1i32))
{Owned<char>(&tmp + j * 1i32)}
```

I'm puzzled because tmp is clearly an array of length >1. Is there a different way we can explicitly define an array like this? Thanks!

**Comment by peterohanley** [comment] 2024-08-25 23:08
This error is because you need to use a `u64` index for all `each` terms. Also you need to return the resource from `readex` (explicitly destroying it with `free` or something isn't possible yet).

```
void readex(char* tmp)
/*@
  requires take a1 = each(u64 j; 0u64 <= j && j < 1u64) { Owned<char>(array_shift<char>(tmp,j)) };
  ensures take a2 = each(u64 j; 0u64 <= j && j < 1u64) { Owned<char>(array_shift<char>(tmp,j)) };
@*/
{
    return;
}

int tmp()
{
    char tmp[2]={'H', 'i'};
    readex(tmp);
    return 1;
}
```

With those changes you get this error:
```
% cn verify issue_533.c
[1/2]: readex -- pass
[2/2]: tmp -- fail
issue_533.c:14:5: error: Cannot satisfy request for resource for de-allocating. It requires merging multiple arrays.
    return 1;
    ^~~~~~~~~ 
Resource needed: Block<char[2]>(&tmp)
  which requires: each(u64 i; 0'u64 <= i && i < 2'u64)
{Block<char>(&tmp + i * 1'u64)}
      other location (Cn__ResourceInference.General.predicate_request)  (arg value)
```
The state file contains these:
```
Requested resource
Block<char[2]>(&tmp)

Available resources
each(u64 j; 0'u64 <= j && j < 1'u64)
{Owned<char>(&tmp + j * 1'u64)}(call_readex0.a2)
each(u64 j; 0'u64 <= j && j < 2'u64 && !(true && 0'u64 <= j && j < 1'u64))
{Owned<char>(&tmp + j * 1'u64)}(const(default(u8))[0'u64 = 72'u8 /* 0x48 */][1'u64 = 105'u8 /* 0x69 */])
```

I guess it can't determine that it can merge these back together. This should be well within the power of Z3's simplifier so I'm not sure what's next.

**Comment by lwli11** [comment] 2024-08-26 12:23
Thanks! Seems it verifies with:
```c
void readex(char* tmp)
/*@
        requires take a1 = each(u64 j; 0u64 <= j && j < 2u64) { Owned<char>(array_shift<char>(tmp,j)) };
        ensures take a2 = each(u64 j; 0u64 <= j && j < 2u64) { Owned<char>(array_shift<char>(tmp,j)) };


@*/
{
        return;
}
char* tmp()
{
        char tmp[2]={'H', 'i'};
        readex(tmp);
        return tmp;
}
```

But there's no way to turn tmp into null?

**Comment by dc-mak** [comment] 2024-08-26 13:58
Can you clarify what you mean by "turn tmp into null"? Returning a pointer to a stack local is UB.

**Comment by lwli11** [comment] 2024-08-26 15:08
Ah, so tmp = {null} isn't considered freeing it.

**Comment by dc-mak** [comment] 2024-08-26 15:15
Block (`{ statements }`) scoped variables are automatically de-allocated upon exiting the scope. So there's nothing to do - the array that `tmp` points to is on the stack and will be de-allocated upon function return.

**Comment by dc-mak** [comment] 2024-08-26 17:16
Actually this is a duplicate of https://github.com/rems-project/cerberus/issues/256 so closing.

**Closed as completed by dc-mak** 2024-08-26 17:16 UTC
Labels: cn
