### ISSUE TITLE
[CN] Crash on switch statement 

### ISSUE THREAD

**Issue by septract** [rems-project/cerberus#241] opened 2024-05-01 18:12 UTC
CN version: e62d18a

Crashing input: 
```
void a() {
  switch (0)
    ;
}
```

Result:
```
% cn switch_crash_1.c 
cn: internal error, uncaught exception:
    Invalid_argument("option is None")
    Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml", line 822, characters 26-56
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml" (inlined), line 697, characters 15-102
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml", line 865, characters 15-24
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml" (inlined), line 697, characters 15-102
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml", line 865, characters 15-24
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml" (inlined), line 697, characters 15-102
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml", line 862, characters 10-19
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml" (inlined), line 697, characters 15-102
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml", line 862, characters 10-19
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml" (inlined), line 697, characters 15-102
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml", line 862, characters 10-19
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml" (inlined), line 697, characters 15-102
    Called from Dune__exe__Core_to_mucore.n_expr in file "backend/cn/core_to_mucore.ml", line 862, characters 10-19
    Called from Dune__exe__Core_to_mucore.normalise_fun_map_decl.(fun) in file "backend/cn/core_to_mucore.ml", line 1297, characters 23-132
    Called from Dune__exe__Core_to_mucore.make_largs.aux in file "backend/cn/core_to_mucore.ml", line 969, characters 16-26
    Called from Dune__exe__Core_to_mucore.make_function_args.aux in file "backend/cn/core_to_mucore.ml", line 1053, characters 18-87
    Called from Dune__exe__Core_to_mucore.normalise_fun_map_decl in file "backend/cn/core_to_mucore.ml", line 1295, characters 7-913
    Called from Dune__exe__Core_to_mucore.normalise_fun_map.(fun) in file "backend/cn/core_to_mucore.ml", line 1356, characters 15-180
    Called from Pmap.fold in file "pmap.ml", line 156, characters 15-38
    Called from Dune__exe__Core_to_mucore.normalise_fun_map in file "backend/cn/core_to_mucore.ml", line 1354, characters 2-746
    Called from Dune__exe__Core_to_mucore.normalise_file in file "backend/cn/core_to_mucore.ml", line 1512, characters 4-172
    Called from Dune__exe__Main.main in file "backend/cn/main.ml", line 179, characters 22-81
    Re-raised at Dune__exe__Main.main in file "backend/cn/main.ml", line 223, characters 8-73
    Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
    Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

**Comment by dc-mak** [comment] 2024-06-06 13:04
Duplicate of https://github.com/rems-project/cerberus/issues/242 fixed by https://github.com/rems-project/cerberus/commit/e47da55f38853eb40beabc758fbf80284056dbcc, closing.

**Closed as completed** 2024-06-06 13:04 UTC
Labels: cn
